Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine317"

  config.vm.define "haboudaS" do |server|
    server.vm.hostname = "haboudaS"
    worker.vm.network "public_network", ip: "192.168.56.110", bridge: "ebp0s8"

    server.vm.provider "virtualbox" do |vb|
      vb.name   = "haboudaS"
      vb.memory = "1024"
      vb.cpus   = 1
    end

    server.vm.provision "shell", path: "scripts/setup.sh", bridge: "vboxnet1"
  end

end
