Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine317"

  # ────────────────────────────────────────────
  #  Machine 1 : haboudaS  (K3s controller)
  # ────────────────────────────────────────────
  config.vm.define "haboudaS" do |server|
    server.vm.hostname = "haboudaS"
    worker.vm.network "public_network", ip: "192.168.56.110", bridge: "ebp0s8"

    server.vm.provider "virtualbox" do |vb|
      vb.name   = "haboudaS"
      vb.memory = "1024"
      vb.cpus   = 1
    end

    server.vm.provision "shell", path: "scripts/setup_server.sh"
  end

  # ────────────────────────────────────────────
  #  Machine 2 : haboudaSW  (K3s agent)
  # ────────────────────────────────────────────
  config.vm.define "haboudaSW" do |worker|
    worker.vm.hostname = "haboudaSW"
    worker.vm.network "public_network", ip: "192.168.56.111", bridge: "ebp0s8"

    worker.vm.provider "virtualbox" do |vb|
      vb.name   = "haboudaSW"
      vb.memory = "1024"
      vb.cpus   = 1
    end

    worker.vm.provision "shell", path: "scripts/setup_worker.sh"
  end

end
